name: mg-emb-exps-dijkstra-tsne
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - anndata==0.10.9
      - matplotlib==3.8.3
      - numpy==1.26.4
      - opentsne==0.6.2
      - scipy==1.13.0rc1
